### ISSUE TITLE
propTypes aren't honored

### ISSUE THREAD

**Issue by coopy** [plotly/dash-html-components#10]
All HTML components have propTypes defined according to the documentation:
https://facebook.github.io/react/docs/reusable-components.html#stateless-functions

The `style` propType is set to `PropTypes.object` for all components.

Yet, when running a basic layout in Dash, we get `propType` warnings:

```
util.js:242 Warning: Failed propType: Invalid prop `style` of type `object` supplied to `Pre`, expected `string`. Check the render method of `UnconnectedContainer`.
```
1. How come `Pre.propTypes = {style: PropTypes.object}` is ignored?
2. Where is the `string` propType coming from?

**Comment by alexcjohnson** [comment]
AFAICT this is fixed, probably long ago. Feel free to reopen with a full example if I'm missing something!
