### ISSUE TITLE
Backwards incompatibility with 1.0.0

### ISSUE THREAD

**Issue by moorepants** [plotly/dash-html-components#120]
It seems the public module `dash_html_components.version` was removed with no deprecation warning.

**Comment by alexcjohnson** [comment]
Thanks @moorepants - we removed that as part of a simplification of the build process (`__version__` is still available as an attribute but the `version` module is no more. Apologies for the oversight, we'll add this in to the changelogs and migration guide. Thanks for pointing this out!
