### ISSUE TITLE
Several components have limited or no functionality in current browsers

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash-html-components#129]
We recently prepared examples for `dashHtmlComponents` in advance of submission to CRAN.

As a result, several components were identified as non-functional or obsolete by those writing up the examples; this is most likely the result of browsers deprecating previously valid HTML elements.

A list of these follows below. :no_entry_sign: indicates a component which is suspected not to function anymore.

From @rpkyle:

- :no_entry_sign: `htmlBasefont`: this HTML5 element is deprecated, but the component does not suit the specifications as written and does not work.

From @CanerIrfanoglu:

- `htmlListing`: Deprecated. Example working.
- `htmlMarquee`: Obsolete. Example working.
- `htmlMeta`: Example added but injects `<meta>` tag to `<body>`. Not sure if this is acceptable.
- `htmlMultiCol`: Obsolete. Example added (requires `col` arg and Netscape 4 to work).
- :no_entry_sign: `htmlNextid`: Needs to be injected in the `<head>` and not supported by any browser.
- :no_entry_sign: `htmlObjectEl`: Example created but not working. `object` tag  has `data` attribute but `htmlObjectEl` does not. There is an [issue](https://github.com/plotly/dash-html-components/issues/66) created earlier.
- `htmlOptgroup`: Example working. However, labels are blank. Noted that `optgroup` should have `label` argument. Below is how it looks vs. how it is supposed to look:
<img width="224" alt="Screen Shot 2019-07-30 at 5 11 45 PM" src="https://user-images.githubusercontent.com/20918264/62165811-42401500-b2ed-11e9-8f17-a567438abe2e.png">                                                  <img width="120" alt="Screen Shot 2019-07-30 at 5 12 15 PM" src="https://user-images.githubusercontent.com/20918264/62165821-48ce8c80-b2ed-11e9-960f-726486234238.png">
- :no_entry_sign: `htmlOutput`: Need `oninput` attribute of `htmlForm` & `htmlInput`(does not exist) to create a working example.
- :no_entry_sign: `htmlParam`: Example added but not working. Depends on `data` attribute of  `htmlObjectEl`
- :no_entry_sign: `htmlPlaintext`: Obsolete. Example added but does not work as intended (should render rest of html as plain-text)

From @sacul-git:

- :no_entry_sign: `htmlScript`: I did not successfully create a minimal `htmlScript` that actually works.
- `htmlShadow`: This is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/shadow), and I'm not sure how to show a meaningful example in the context of a Dash app.
- `htmlSlot`: I'm not sure how to show a meaningful example in the context of a Dash app.
- `htmlSpacer`: [non-standard and obsolete](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/spacer)
- `htmlTitle`: Because an app's title is set through `Dash$new(name = "title")`, I'm not sure how to show a meaningful example of `htmlTitle`.
- `htmlTrack`: Not sure how to use this within a Dash app with audio or video, and if there is a way, I'm not sure where I should source a `vtt` file from.

@alexcjohnson

**Comment by rpkyle** [comment]
I motion to deprecate the following components in the next `dash-html-components` and `dashHtmlComponents` releases, as they are no longer functional/supported in modern browsers:

- `htmlBasefont`: only works with Microsoft browsers, see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/basefont)
- `htmlBlink`: not supported by any widely used modern browser, see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blink)
- `htmlCommand`: not supported by any widely used modern browser, see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/command)
- `htmlElement`: does not appear to be supported by widely used modern browsers, see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/element)
- `htmlIsindex`: not supported by any widely used modern browser, see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/isindex)
- `htmlListing`: not supported by any widely used modern browser, see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/listing)
- `htmlMarquee`: not supported by any widely used modern browser, see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee)
- `htmlMulticol`: not supported by any widely used modern browser, see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/multicol)
- `

**Comment by HammadTheOne** [comment]
`htmlContent` should also be removed if `htmlShadow` is being removed. It is used inside of `Shadow DOM` and is also deprecated and not supported by any widely used modern browser, see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/content).

**Comment by rpkyle** [comment]
Following a discussion offline, we've made the decision to retain the above components. Closing this issue.

**Comment by mbauman** [comment]
I'd kindly ask for reconsidering here — I understand that the components are dynamically generated, but the fact that the _documentation_ is also dynamically generated makes it seem like these are fully functional bits and bobs to put into a dash.

In particular, even though `<script>` is a _very_ functional HTML element it'll _never work_ in a dash (as it currently stands) because browsers don't execute `<script>`s inserted in the way react does it (via innerHTML).  Including it in the documentation only leads folks down dead ends.  Either it should use a different insertion mechanism, or it should have a bright bit warning in the docs, or it should be removed entirely.

**Comment by alexcjohnson** [comment]
I do agree we should keep these components around. `script` in particular has some other uses like storing data. Typically this is used for the back-end to pass data to the front end on page load, but one could imagine scenarios where this is useful when Dash is part of a larger app, to pass data between pieces of that app.

But @mbauman is right that we should document these limitations better. Reopening as a documentation issue.

**Comment by rpkyle** [comment]
_Possibly_ relevant to plotly/dashR#243, since we may want to document within the package also.
