### ISSUE TITLE
`html.Label` should be able to support the `for` attribute

### ISSUE THREAD

**Issue by ned2** [plotly/dash-html-components#144]
The `html.Label` component does not support the `for` attribute, presumably because it's a Python reserved keyword. 

It would be desirable to support this attribute somehow, in order to enable linking the label with associated input controls. As mentioned by [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) This helps makes pages more accessible with screen readers and clicking on the label will also activate the relevant input.

This can currently be achieved by nesting the input within a label, however this doesn't allow as much flexibility of page layout as using the `for` attribute to link to the input's ID.

**Comment by alexcjohnson** [comment]
Thanks @ned2 - this came up in https://github.com/plotly/dash/issues/878 but as discussed there it's a bit distinct, since this is also a JS reserved word. Fortunately, that means React already had to figure this out, we should just defer to their solution: `htmlFor`.

**Comment by ned2** [comment]
Oh cool, `htmlFor` is already supported by `html.Label`! 

Missed that. I think this can be closed then.

**Comment by alexcjohnson** [comment]
oh haha I hadn't even looked - I thought we still needed to add it, but there it is 🎉
