### ISSUE TITLE
generate-components components generates buggy entry for nextid element 

### ISSUE THREAD

**Issue by ned2** [plotly/dash-html-components#25]
When I run `npm run generate-components`, I get an unhappy looking component file in `src/components`: `Nextid: the next id element (obsolete).react.js` and a correspondingly bogus line in index.js:

    import Nextid: the next id element (obsolete) from './components/Nextid: the next id element (obsolete).react';

Apparently this element is deprecated. Might this be the problem?

**Comment by chriddyp** [comment]
Yeah, so the `generate-components` command runs a few scripts that scrape MDN to extract component definitions. MDN changes frequently, so sometimes the content on their site doesn't get scraped correctly. There is a line in the script that allows you to exclude elements here: https://github.com/plotly/dash-html-components/blob/6d04a70f098bb8640545467255ae382e8e17cffb/scripts/extract-elements.js#L15

**Comment by ned2** [comment]
Cool thanks. Not sure that adding it to `excludeElements` makes a lot of sense because its value within the `<td>` that would need to be batched against is `nextid: the next id element (obsolete)`. So I added an extra filtering step to make sure tag names occur with opening and closing angle brackets. ie:

    .filter(element => cheerio(element).text()[0] === '<')

However it also looks like that page has changed a lot since the script was last run. I had to add the following elements as they don't appear as rows in that table anymore:

    'title', 'base', 'p', 'a', 'b', 'col', 'em', 'link', 'ol', 'q', 's', 'tr', 'u', 'ul', 'i', 'li', 'embed'

The obsolete 'image' tag also appears in the table now so gets a component generated for it.  This is perhaps a separate  issue, but was wondering if perhaps the obsoleted and deprecated tags could be excluded. 

Here's my modified `extractElements`:

```
function extractElements($) {
    const excludeElements = [
        'html', 'head', 'body', 'style', 'h1–h6', 'input'
    ];
    const obsoleteElements = [
        'acronym', 'applet', 'basefont', 'big', 'blink', 'center', 'command',
        'content', 'dir', 'element', 'font', 'frame', 'frameset', 'image',
        'isindex', 'keygen', 'listing', 'marquee', 'multicol', 'nextid',
        'noembed', 'plaintext', 'shadow', 'spacer', 'strike', 'tt', 'xmp'
    ];
    const filterElements = excludeElements + obsoleteElements;
    // `<section>` is for some reason missing from the reference tables.                                                                                                      
    const addElements = [
        'h1', 'h2', 'h3', 'h4','h5', 'h6', 'iframe', 'title',
        'base', 'p', 'a', 'b', 'col', 'em', 'link', 'ol',
        'q', 's', 'tr', 'u', 'ul', 'i', 'li', 'embed'
    ];

    return $('td:first-child')
        .toArray()
        .filter(element => cheerio(element).text()[0] === '<')
        .map(el => {
            return cheerio(el).text().replace(/[\<\>]/g, '');
        })
        .reduce((list, element) => {
            const subList = element.split(', ');
            return list.concat(subList);
        }, [])
        .filter(element => filterElements.indexOf(element) === -1)
        .concat(addElements);
}

```

Perhaps it might be cleaner to target the list of elements on the left hand side of the page? Seeing as that table seems to be in a fair bit of flux, meaning that white and black lists of tags will need continual updating.

I'd be happy to put together a PR for that.

**Comment by ned2** [comment]
The MDN page has now been changed again to fix the initial issue and the missing tags that I mentioned have come back! Perhaps others were also scraping the page. I shall therefore close this.

**Comment by chriddyp** [comment]
Thanks for the update @ned2 !
