### ISSUE TITLE
Cannot use HTML tags in children text

### ISSUE THREAD

**Issue by felixvelariusbos** [plotly/dash-html-components#30]
It seems like when I add HTML to an html_component children text, it is somehow keeping the browser from parsing it into anything but plain text. For example, trying to use an `<a>` tag results in the actual text `<a>` instead of a link.

An example to clarify:

`    html.Div('If you\'re interested in viewing trends, please' +
             ' check out <a href="https://trends.google.com" target="_blank"> Google Trends</a>' +
             ' for more information.'
            ),`

This results in being displayed on the webpage as:

`If you're interested in viewing trends, please checkout <a href="https//trends.google.com" target="_blank"> Google Trends</a> for more information.
`

**Comment by chriddyp** [comment]
That's right - React.js will always escape the text (for security reasons). The proper solution to this will be to provide a `DangerouslySetInnerHTML` component that allows raw text by using React's `dangerouslySetInnerHTML` function https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml

**Comment by chriddyp** [comment]
I have created a dangeroulsySetInnerHTML component that you can use https://github.com/plotly/dash-dangerously-set-inner-html. However, I recommend using the `dash-html-components` as much as possible.

**Comment by felixvelariusbos** [comment]
It makes sense if it's for security purposes, and there's ways to get around it if I need to (for example using dcc.Markdown instead or just making a string of html components to achieve the same purpose). Since it's just kind of a convenience to be able to put in straight HTML, I don't mind giving that up for the sake of security!
 
Thank you for the quick response!
