### ISSUE TITLE
Td attribute does not support more than 1 argument

### ISSUE THREAD

**Issue by mark9064** [plotly/dash-html-components#42]
For example, trying to put an input inside a Td, followed by some text results in the following error:
`TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given`
If I am reporting this bug in the wrong repository please redirect me
Thanks in advance

**Comment by ned2** [comment]
As with all Dash Components,` html.Td` takes an optional keyword argument `children`, which can be used without the keyword if used as the first argument. This argument takes either a single `Component` or a list of `Component` objects. So if you want your `html.Td` to have multiple components/elements within it, you should use a list. eg:

 `html.Td([dcc.Input(id='foo'), 'Some text'])`

**Comment by mark9064** [comment]
Thank you very much, fixed my problem :smile:
