### ISSUE TITLE
failed to install metadata.json and manifest.md missing

### ISSUE THREAD

**Issue by ivs17** [plotly/dash-html-components#43]
Hey,
No idea what is necessary to recreate this error ( bloody n00b)...

but installing this via 
$ python setup.py install 
on anaconda (not available on anaconda cloud anyway for windows)
the resulting error using
$  import dash_html_components
was 
$ FileNotFoundError: [Errno 2] No such file or directory: 'E:\\anaconda3\\lib\\site-packages\\dash_html_components-0.10.0-py3.6.egg\\dash_html_components\\metadata.json'

aswell as the "manifest.md" file

Of course, I might have skipped sth. in the installation process.
Copying the files manually from git into the folders where they were expected seemed to solve the issue...for now...
( was able to run dash-stock-tickers-demo-app-master and )

**Comment by chriddyp** [comment]
instead of installing from the repo, install using pip:
pip install dash-html-components

the pip version is the “built” version which includes these files. see dash.plot.ly/installation for more
