### ISSUE TITLE
PropType for n_clicks and n_clicks_timestamp is not valid

### ISSUE THREAD

**Issue by pbugnion** [plotly/dash-html-components#49]
First of all, thanks very much for making Dash! We use it a lot.

*dash-html-components* defines the prop type for `n_clicks` and `n_clicks_timestamp` as `integer` [here](https://github.com/plotly/dash-html-components/blob/master/scripts/generate-components.js#L57). That's not, as far as I can tell, valid prop types (see [a list of PropTypes here](https://github.com/facebook/prop-types)). The correct prop type is `number`. 

This doesn't seem to stop react-docgen from creating the correct metadata, but it does make it confusing for people developing new components that depend on the HTML components. If you enable prop types checking, you get lots of errors about `n_clicks` and `n_clicks_timestamp` being invalid.

Am I missing something here? Is there a good reason why this should be `integer` instead of `number`? If not, I'm very happy to submit a PR.

----

*Reproducing the issue*

The quickest route to reproducing the issue is to start from the [documentation on creating custom components](https://dash.plot.ly/plugins).

```
builder-init dash-components-archetype
npm install --save dash-html-components
```

We now need to enable prop types checking. The easiest is to remove the declaration that `React` and `ReactDOM` are external dependencies in 
`node_modules/dash-components-archetype/config/webpack/webpack.config.js`. This means we actually get warnings for bad propTypes.

Now change `demo/Demo.react.js` to this:

```javascript
import React, {Component} from 'react';
import {ExampleComponent} from '../src';

import {dash_html_components} from 'dash-html-components/lib/bundle';
const {Details} = dash_html_components;

const Demo = props => {
    return (
	<div>
	    <h1>reproduce-dash-error Demo</h1>

	    <h2>Example details</h2>
	    <Details>
		<p>Hello inside details</p>
		<summary>Hello summary</summary>
	    </Details>
	    <hr/>

	</div>
    );
}

export default Demo
```

Now run:
```
npm run demo
```

In the browser console, you can see:

<img width="1081" alt="screen shot 2018-06-24 at 14 07 09" src="https://user-images.githubusercontent.com/1392879/41819486-11d389b2-77b9-11e8-8662-5c9b78e7c6cd.png">

You can make the errors go away by explicitly overriding the prop types:

```js
Details.propTypes = {
    ...Details.propTypes,
    n_clicks: PropTypes.number,
    n_clicks_timestamp: PropTypes.number
}
```

**Comment by chriddyp** [comment]
Thanks for reporting @pbugnion ! I think that this was just an typo on my end 🙈 Sorry for the confusion!

Would definitely 👍 a PR to fix this
