### ISSUE TITLE
Using the object tag with data property

### ISSUE THREAD

**Issue by pandeymanishh** [plotly/dash-html-components#66]
for a small dash app I am working , I also need to display an embedded PDF in a section.
While using HTML I could do something like this to display the PDF.
`	<object type="application/pdf" data="sample.pdf#toolbar=1&navpanes=1&scrollbar=1&page=25" width="500" height="375"	>`

I am unable to replicate this within dash.I am using the ObjectEl html component(I believe this is the corresponding element for HTML object tag), but it doesn't have a data property to set.

Any suggestion would be highly appreciated!

Thanks.

**Comment by alexcjohnson** [comment]
more info in #161 so closing this one
