### ISSUE TITLE
missing some attributes for `Iframe`?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-html-components#77]
- frameborder
- scrolling

**Comment by oxydaemon** [comment]
Also missing "allow" attribute

(https://community.plot.ly/t/using-keywords-in-dash-iframe/13485)

**Comment by HunGYuHeng** [comment]
Missing "allowfullscreen" attribute,too.

**Comment by Martiix** [comment]
autoplay (allow) and loop attribute would be nice.

**Comment by chriddyp** [comment]
Until these are available, one solution would be to use 
```
    dash_dangerously_set_inner_html.DangerouslySetInnerHTML('''
        <iframe ...
    '''),
```

as per https://github.com/plotly/dash-dangerously-set-inner-html

This is still a good issue and one worth fixing.

**Comment by cassova** [comment]
Are there any updates on supporting features like the `allowFullScreen` for embedded youtube videos?

**Comment by alexcjohnson** [comment]
This hasn't bubbled up to the top of the list for anyone at Plotly yet, but we'd be happy to review a PR!
